import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FullPageNav from "@/components/Navbar.component";
import { CursorProvider } from "@/context/CursorContext";
import { AudioProvider } from "@/context/AudioContext";
import MouseCursorComponent from "@/components/MouseCursor.component";
import BackgroundAudioComponent from "@/components/BackgroundAudio.component";
import LogoComponent from "@/components/Logo.Component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen relative">
          <CursorProvider>
            <AudioProvider>
              <MouseCursorComponent />
              <BackgroundAudioComponent />
              <LogoComponent />
              <FullPageNav />
              {children}
            </AudioProvider>
          </CursorProvider>
        </div>
      </body>
    </html>
  );
}
